# -*- coding: utf-8 -*-
"""solutions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RojgAtG8S0OdkgYweMbInop_yKTyUkXp

**Bài tập Python**
---

# CƠ BẢN

## Vòng lặp

**Bài 1** Nhập vào số nguyên dương n. Tính tổng 1 + 2 + ... + n
"""

n = int(input("Nhập n: "))
tong = 0
for i in range(1, n+1):
  tong += i

print(f'\nTổng là: {tong}')

"""**Bài 2** Nhập vào số nguyên dương n. Cho biết n có bao nhiêu chữ số. Tính tổng các chữ số của n


"""

n = int(input("Nhập n: "))

print(f'\nSố chữ số của n là: {len(str(abs(n)))}')

"""**Bài 3** In ra các số nguyên tố từ 1..100


"""

def kiem_tra_nguyen_to(number):
  '''
  Kiểm tra một số nguyên dương có phải là số nguyên tố hay không?
  '''
  dem_uoc_so = 0
  for i in range(1, number+1):
    if number%i==0:
      dem_uoc_so += 1

  return (dem_uoc_so==2)

# In các số nguyên tố
# for num in range(1, 101):
#   if kiem_tra_nguyen_to(num):
#     print(num)

# [num for num in range(1, 101) if kiem_tra_nguyen_to(num)]

list(filter(kiem_tra_nguyen_to, range(1, 101)))

"""**Bài 4** Nhập số nguyên dương n. In ra số đảo ngược của n"""

n = int(input("Nhập n: "))
tam = str(n)[::-1]

print(f'\nSố đảo ngược của n là: {int(tam)}')

# Ghi chú: Đoạn code trên sai trong trường hợp n âm.

"""## Lớp chứa

**Bài 5** Nhập vào hai mảng các số nguyên a và b. Thực hiện các công việc sau:

	1. Xuất các mảng đã nhập
	2. Xuất các mảng đã nhập theo thứ tự đảo ngược
	3. Ghép hai mảng lại thành một mảng c. Xuất mảng c sau khi ghép
	4. Xuất các phần tử ở vị trí chẵn của mảng c
	5. Xuất 3 phần tử cuối cùng của mảng c
	6. Xuất các phần tử là số lẻ trong mảng
	7. Thay thế các phần tử âm trong mảng c bằng số 0
	8. Sắp xếp các phần tử trong c theo thứ tự giảm dần

"""

# 0. Nhập mảng
# txt = "3, 4, 1, 8, 6, 7"
# a = list(map(int, txt.split(",")))
# print(a)

a = list(map(int, input('Nhập mảng a: ').split(",")))

b = list(map(int, input('Nhập mảng b: ').split(",")))

# 1. Xuất các mảng đã nhập
print(f'Mảng a: {a}')
print(f'Mảng b: {b}')

# 2. Xuất các mảng đã nhập theo thứ tự đảo ngược
print(f'Mảng a đảo ngược: {a[::-1]}')
print(f'Mảng b đảo ngược: {b[::-1]}')

# 3. Ghép hai mảng lại thành một mảng c. Xuất mảng c sau khi ghép
c = a + b
print(f'Mảng mới sau khi ghép: {c}')

# 4. Xuất các phần tử ở vị trí chẵn của mảng c
c[::2]

# Xuất các phần tử ở vị trí lẻ
# c[1::2]

# 5. Xuất 3 phần tử cuối cùng của mảng c
c[-3:]

# 6. Xuất các phần tử là số lẻ trong mảng
[num for num in c if num%2]

# 7. Thay thế các phần tử âm trong mảng c bằng số 0
for i in range(len(c)):
  if c[i]<0:
    c[i] = 0

print(c)

# 8. Sắp xếp các phần tử trong c theo thứ tự giảm dần
c.sort(reverse = True)
c

"""
**Bài 6** Viết chương trình yêu cầu nhập thông tin danh sách học sinh (mã, họ tên, điểm toán, điểm ngữ văn, điểm anh văn). Thực hiện các công việc sau:

	1. Lưu thông tin các học sinh vào một **dict** có tên `dshs`
	2. Hiển thị thông tin các học sinh đã nhập
	3. Thêm một thông tin điểm trung bình vào mỗi học sinh bằng cách tính trung bình dựa vào 3 cột điểm đã nhập. HIển thị thông tin các học sinh kèm điểm trung bình
	4. Lưu thông tin các học sinh vào một **list** có tên `ds` . Sắp xếp lại `ds` theo thứ tự giảm dần của điểm trung bình và hiển thị thông tin sau khi đã sắp xếp"""

# Nhập danh sách học sinh (giả sử thông tin mỗi học sinh lưu trong một chuỗi)
# txt1 = '1, Nguyen Van An, 7, 8.5, 9' 
# txt2 = '2, Tran Binh, 4, 10, 5.5'
# txt3 = '3, Le Minh, 8, 7.5, 6.5'

def lay_thong_tin_hs(chuoi):
  '''
  Trả về list chứa thông tin học sinh

  Input: chuoi: chuỗi chứa thông tin học sinh
  '''
  thong_tin = chuoi.split(',')
 
  thong_tin[0] = int(thong_tin[0])       # Mã học sinh là số nguyên
  thong_tin[1] = thong_tin[1].strip()   # Loại bỏ khoảng trắng đầu và cuối chuỗi

  # Chuyển đổi các điểm sang số thực
  for i in [2, 3, 4]:
    thong_tin[i] = float(thong_tin[i])

  # Tính điểm trung bình
  dtb = (thong_tin[2] + thong_tin[3] + thong_tin[4]) / 3
  thong_tin.append(dtb)
  
  return thong_tin

dshs = {}

soluong = int(input('Nhap so luong hoc sinh: '))
for i in range(soluong):
  hs = lay_thong_tin_hs(input('Nhap thong tin hoc sinh: '))
  dshs[hs[0]] = hs[1:]

print(dshs)

# Xuat danh sach hoc sinh
def hien_thi_ds(ds):
  '''
  Hiển thị danh sách học sinh

  Input: ds: dict
  '''
  for key in ds:
    print(f'\n\t- {key}, {ds[key][0]}, {ds[key][1]}, {ds[key][2]}, {ds[key][3]}')

print(dshs)

hien_thi_ds(dshs)

from prettytable import PrettyTable

t = PrettyTable(['Mã', 'Họ tên', 'Toán', 'Văn', 'Anh', 'DTB'])

# Xuat danh sach hoc sinh
def hien_thi_bang_ds(ds):
  '''
  Hiển thị danh sách học sinh

  Input: ds: dict
  '''
  for key in ds:
    # t.add_row([key, ds[key][0], ds[key][1], ds[key][2], ds[key][3], ds[key][4]])
    t.add_row([key, ds[key][0], ds[key][1], ds[key][2], ds[key][3], '{:.2f}'.format(ds[key][4])])
    
  print(t)

hien_thi_bang_ds(dshs)

# 4. Lưu thông tin các học sinh vào một **list** có tên `ds` . Sắp xếp lại `ds` theo thứ tự giảm dần của điểm trung bình 
# và hiển thị thông tin sau khi đã sắp xếp

# Your code here
# ...